jdbc:
driver: com.mysql.jdbc.Driver
server:
  port: 8081
spring:
  profiles:
    active: dev
    
---

spring:
  profiles: dev
jdbc:
  url: jdbc:mysql://192.168.1.102:3306/p2p?useUnicode=true&characterEncoding=utf8
  username: root
  password: 